export type ThemeMode = 'light' | 'dark';

export interface ColorTokens {
  background: string;
  onBackground: string;
  surface: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  onSurface: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  primaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixed: string;
  onPrimaryFixedVariant: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  secondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixed: string;
  onSecondaryFixedVariant: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  tertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixed: string;
  onTertiaryFixedVariant: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  surfaceTint: string;
}

export const colorTokens: Record<ThemeMode, ColorTokens> = {
  light: {
    background: '#fff8f2',
    onBackground: '#1f1b15',
    surface: '#fff8f2',
    surfaceDim: '#e1d9ce',
    surfaceBright: '#fff8f2',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#fbf2e8',
    surfaceContainer: '#f5ede2',
    surfaceContainerHigh: '#f0e7dc',
    surfaceContainerHighest: '#eae1d7',
    onSurface: '#1f1b15',
    onSurfaceVariant: '#4e4637',
    outline: '#807665',
    outlineVariant: '#d1c5b2',
    primary: '#795901',
    onPrimary: '#ffffff',
    primaryContainer: '#c9a14a',
    onPrimaryContainer: '#4e3800',
    primaryFixed: '#ffdea0',
    primaryFixedDim: '#ecc166',
    onPrimaryFixed: '#261a00',
    onPrimaryFixedVariant: '#5c4300',
    secondary: '#46617c',
    onSecondary: '#ffffff',
    secondaryContainer: '#c1ddfd',
    onSecondaryContainer: '#46617d',
    secondaryFixed: '#cfe5ff',
    secondaryFixedDim: '#adc9e9',
    onSecondaryFixed: '#001d33',
    onSecondaryFixedVariant: '#2d4963',
    tertiary: '#5f5e5e',
    onTertiary: '#ffffff',
    tertiaryContainer: '#a8a6a6',
    onTertiaryContainer: '#3c3c3c',
    tertiaryFixed: '#e5e2e1',
    tertiaryFixedDim: '#c8c6c5',
    onTertiaryFixed: '#1b1b1b',
    onTertiaryFixedVariant: '#474746',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    inverseSurface: '#343029',
    inverseOnSurface: '#f8efe5',
    inversePrimary: '#ecc166',
    surfaceTint: '#795901',
  },
  dark: {
    background: '#1c1c1c',
    onBackground: '#e7e2d8',
    surface: '#141210',
    surfaceDim: '#141210',
    surfaceBright: '#3e3a32',
    surfaceContainerLowest: '#0f0d0b',
    surfaceContainerLow: '#22201b',
    surfaceContainer: '#27241f',
    surfaceContainerHigh: '#322e28',
    surfaceContainerHighest: '#3d3932',
    onSurface: '#e7e2d8',
    onSurfaceVariant: '#c9bdaa',
    outline: '#928877',
    outlineVariant: '#4d4639',
    primary: '#ecc166',
    onPrimary: '#3f2e00',
    primaryContainer: '#5c4300',
    onPrimaryContainer: '#ffdea0',
    primaryFixed: '#ffdea0',
    primaryFixedDim: '#ecc166',
    onPrimaryFixed: '#261a00',
    onPrimaryFixedVariant: '#5c4300',
    secondary: '#adc9e9',
    onSecondary: '#173248',
    secondaryContainer: '#2d4963',
    onSecondaryContainer: '#c1ddfd',
    secondaryFixed: '#cfe5ff',
    secondaryFixedDim: '#adc9e9',
    onSecondaryFixed: '#001d33',
    onSecondaryFixedVariant: '#2d4963',
    tertiary: '#c8c6c5',
    onTertiary: '#303030',
    tertiaryContainer: '#474746',
    onTertiaryContainer: '#e5e2e1',
    tertiaryFixed: '#e5e2e1',
    tertiaryFixedDim: '#c8c6c5',
    onTertiaryFixed: '#1b1b1b',
    onTertiaryFixedVariant: '#474746',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    inverseSurface: '#e7e2d8',
    inverseOnSurface: '#343029',
    inversePrimary: '#795901',
    surfaceTint: '#ecc166',
  },
};
